name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Update Build Server
    #  run: sudo apt-get update
    - name: Dependencies
      run: sudo apt-get install -y libgtk-4 build-essential
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
